### ISSUE TITLE
Conditional imports based on version?

### ISSUE THREAD

**Issue by valencik** [netromdk/vermin#1]
Very cool project!

I am wonder if it might be able to be extended to handle `import` statement that are conditional on the python version. For example, the following python code works in python 2 and 3 but the minpy output seems unsure:

```python
import sys
is_py2 = sys.version[0] == '2'
if is_py2:
    import Queue as Queue
else:
    import queue as Queue
```

minpy:

```
'Queue' requires (2.0, None)
'queue' requires (None, 3.0)
Versions could not be combined: [2.0, None] and (None, 3.0)
File with incompatible versions: /Users/valencik/projects/scrap/test_imports.py
Note: Some files had incompatible versions so the results might not be correct!
Could not determine minimum required versions!
```

Perhaps there's a more canonical way to branch on versions that I am unaware of.

**Comment by netromdk** [comment]
Thank you for the interest!

Minpy is actually saying that `Queue` only works in v2 and that `queue` only works in v3. Thus they are incompatible. Maybe it could be written better in the output to communicate this? Could be by writing `'Queue' only works with v2`, for instance, and similar?

I've been thinking about how this could be detected better, and the only way to do this is by knowing which branch to follow in the code, like the `if is_py2:` or `else:` branches in your example. 

And it gets more difficult because there are other ways of doing these conditional imports, like
```py
try:
    import simplejson as json
except ImportError:
    import json
```

**Comment by netromdk** [comment]
A little extra info from a [reddit discussion](https://www.reddit.com/r/Python/comments/81wv0e/detect_minimum_python_versions_required_to_run/dv6zuru/).
