### ISSUE TITLE
Vermin fails to detect invalid syntax for Python 3.7

### ISSUE THREAD

**Issue by Wenzel** [netromdk/vermin#129]
**Describe the bug**
An unpacking invalid syntax is not detected by vermin as incompatible with Python 3.7, and requires at least Python 3.8

**To Reproduce**
~~~python3
from typing import Tuple
a: Tuple[str, int] = "vermin", 4
print(type(a))
~~~

**Expected behavior**
Vermin should have warned that this code requires at least Python3.8

**Actual behavior**
~~~
Minimum required versions: ~2, ~3
Note: Not enough evidence to conclude it won't work with Python 2 or 3.
~~~

With Python3.7.15
~~~
  File "test.py", line 2
    a: Tuple[str, int] = "vermin", 4
                                 ^
SyntaxError: invalid syntax
~~~

**Environment (please complete the following information):**
 - Vermin version: 1.5.1

**Comment by netromdk** [comment]
Thanks for reporting this. I'm going to look into it soon.

**Comment by netromdk** [comment]
Excuse the long wait. Busy times.

The problem is that if you get a syntax error, it happens before we can parse the abstract syntax tree since we're using Python's own, built-in parser. This is also why I recommend to use the newest possible Python installation at all times. One thing you can conclude from such a syntax error is that either you've written something wrong or you're indeed using a feature newer than the interpreter supports.

If you use verbose level 2 or higher (`-vv`), you can see Vermin also says there's a syntax error:
```
% python3.7 vermin.py -vv test.py
test.py:2:30:error: invalid syntax: a: Tuple[str, int] = "vermin", 4
~2, ~3       test.py
Minimum required versions: ~2, ~3
Note: Not enough evidence to conclude it won't work with Python 2 or 3.
```

You can also use pessimistic mode:
```
  --pessimistic
        Pessimistic mode: syntax errors are interpreted as the major Python version
        in use being incompatible.
```

Then at least it'd always report the major Python version as being incompatible because of the syntax error (also without verbose level 2+):
```
% python3.7 vermin.py -vv --pessimistic test.py
test.py:2:30:error: invalid syntax: a: Tuple[str, int] = "vermin", 4
~2, !3       test.py
Minimum required versions: ~2
Note: Not enough evidence to conclude it won't work with Python 2.
Incompatible versions:     3

% python3.7 vermin.py --pessimistic test.py
Minimum required versions: ~2
Note: Not enough evidence to conclude it won't work with Python 2.
Incompatible versions:     3
```

Since Vermin is using Python's own parser, it only knows about the features of its own version. And therefore there isn't much else to do than use a newer Python version.

I hope this helps.
