### ISSUE TITLE
Take sys.version_info checks into account

### ISSUE THREAD

**Issue by osandov** [netromdk/vermin#221]
**Is your feature request related to a problem? Please describe.**

`vermin` doesn't seem to take `sys.version_info` checks into account, so the following code is incorrectly marked as requiring Python 3.8:

```
$ cat test.py
if sys.version_info >= (3, 8):
    _open_code = io.open_code
else:
    from typing import BinaryIO

    def _open_code(path: str) -> BinaryIO:
        return open(path, "rb")
$ vermin --no-tips -t=3.6- ./test.py
Minimum required versions: 3.8
Incompatible versions:     2
Target versions not met:   3.6-
```

**Describe the solution you'd like**

It'd be nice if vermin considered `sys.version_info` when determining the minimum version. Maybe each branch behind a version check could be checked for compatibility with the stated version.

**Describe alternatives you've considered**

This can currently be worked around with `# novermin`.

**Additional context**

My project, [drgn](https://github.com/osandov/drgn), just started using `vermin` via pre-commit. The only two places we had to add `# novermin` were:

https://github.com/osandov/drgn/blob/9d7f70aeaa08578566c77c0d068b77c168eee4ae/drgn/__init__.py#L144-L150

https://github.com/osandov/drgn/blob/9d7f70aeaa08578566c77c0d068b77c168eee4ae/vmtest/rootfsbuild.py#L11-L15

Both are inside of `sys.version_info` checks.

**Comment by netromdk** [comment]
Hi there. Thank you for the feedback.

Unfortunately, this is not possible because it would require Vermin to execute the code in order to know, at run-time, which branch that would be taken. Executing code can have destructive side-effects, which is why it is not done. Vermin does static analysis only.

This has been brought up before. Take a look here for more information: https://github.com/netromdk/vermin/issues/147#issuecomment-1419649657
