### ISSUE TITLE
Handling Backported Packages

### ISSUE THREAD

**Issue by ngtvspc** [netromdk/vermin#29]
**Is your feature request related to a problem? Please describe.**
When using the [backported `typing` module](https://pypi.org/project/typing/) vermin indicates the files using it are not compatible with any version of py2. This is not correct, as this module is compatible with 2.7+ and 3.4+. It is flagging this usage of `typing` because it was not included in the standard library until version [3.5](https://docs.python.org/3/library/typing.html?highlight=typing#module-typing).

**Describe the solution you'd like**
One solution we were discussing was giving `vermin` the capability to parse a projects `requirements.txt` and give the user the ability to disable rules based on conflicts in the `requirements.txt`

However after discussing this with some of my co-workers, (I knew I was missing something obvious), the package name specified to PyPI doesn't necessarily have anything to do with the imported module name. Simply parsing the `requirements.txt` isn't a robust solution.

**Describe alternatives you've considered**
I'm at a loss here for good ideas. I would really like to support something as official as a backport of a standard library. Perhaps `vermin` could classify certain errors as warning instead, and caution the user that they need to have `typing` installed to work with py2. Have you considered anything along those lines? A lot of other static analysis tools make a clear distinction between different types of issues. (Critical, Error, Warning, Info, etc.)

**Additional context**
This feature is mostly stemming from my usage of `vermin`, which is primarily to analyze applications and collect statistics about their py2/3 compatibility.

**Comment by netromdk** [comment]
It's a good point that we can't necessarily rely on the names of the packages used. Additionally, there are more package repositories, too.

First, even though it's not a perfect solution, I'd like to reiterate that one can use `--exclude typing` CLI argument to exclude `typing` rules since the user knows he/she is using a backported module.

However, maybe what's needed are CLI arguments to tell Vermin the certain backported modules are used. It might be something like `--backport typing` with a help text that describes which ones are currently supported and maybe with rough min/max versions info. Maybe the rules could be altered for such cases similar to:
```py
"typing": ((2, 7), (3, 4)) if backport("typing") else (None, (3, 5)),
```
Just to show one of the rules.

Thoughts?

**Comment by netromdk** [comment]
Additionally, a tip could be printed to stdout asking the user if he/she is using any backported modules such as typing (we can actually just look it up since the information is there), and that it would probably make sense to run with `--backport typing` (and enumerate if other known ones in use, if any).

Example:
```
Tip: You're using potentially backported modules: typing, other_one
If so, try using `--backport typing --backport other_one` for better results.
```

And maybe in general a `--no-tips` argument to silence such things.

**Comment by ngtvspc** [comment]
I am using the `--exclude` option for now and my commands have started to look like this:
`vermin --exclude typing --exclude typing.Text --exclude typing.Type .` in order to skip those `typing` related rules. This does also raise the question: should exclusion of a module also exclude it's members? I think it should. 

I think a `backport` option is much closer to what we want than a `requirements` option. And I do like the idea of tips that will help guide usage of `vermin`. I'm a little concerned about how to properly extend the definition of rules to support something like backported packages, I'd love to maintain the current level of simplicity in the rule definitions.

@mahmoud, who's also working on the project where we're using `vermin`, what do you think?

**Comment by netromdk** [comment]
Currently you have to name everything to exclude so as not to exclude more than necessary. Also, there's a difference to the `typing` module and `typing.Text` and `typing.Type` classes. However, maybe a wildcard `*` could be introduced since it's not allowed in the names anyway, like `--exclude typing*`. But it's a little more complex since it also supports excluding kwargs (`--exclude 'somemodule.func(foo)'`), codecs error handlers (`--exclude 'ceh=bar'`), and codecs encodings (`--exclude 'ce=baz'`). Should be doable though.

I agree about the rules. I don't want to "pollute" them more than necessary. To keep things simple, I would like to keep the dictionary of tuples of tuples. I don't find it too horrible what I suggested above, though.

Any feedback is welcome.

**Comment by mahmoud** [comment]
My only feedback at this time (my vacation time :P) is that backports are pretty core to migration processes I've seen, so I think handling them smoothly is pretty critical. I'll keep an eye on this issue and any associated PRs. Keep up the good work!

**Comment by netromdk** [comment]
Thanks for the feedback. :)

I have preliminary support for the `typing` backport in the [backports](https://github.com/netromdk/vermin/tree/backports) branch, that I hope to finish tonight.

Are there any other important backports to add support for initially, @ngtvspc @mahmoud ?

**Comment by netromdk** [comment]
Maybe some of these that doesn't have support for 2.7 in the standard already: https://wiki.python.org/moin/StandardLibraryBackports

Like: [faulthandler](https://pypi.org/project/faulthandler/), [configparser](https://pypi.org/project/configparser/), [subprocess32](https://pypi.org/project/subprocess32/), [unittest2](https://pypi.org/project/unittest2/) just to name a few. But only for well-defined, mature backports that are uses "in the wild".

**Comment by ngtvspc** [comment]
I think the only other one I would have suggested was `enum` because that's one that pops up in my usage of `vermin` a lot, but you've already handled it.

**Comment by netromdk** [comment]
That's great. Then we'll see how it'll be received. 🤘
