### ISSUE TITLE
 Bytes literal reported as requiring 3+ instead of 2.6+

### ISSUE THREAD

**Issue by alalazo** [netromdk/vermin#32]
**Describe the bug**
A Python file containing a byte literal like `b'foo'` is reported to require Python versions greater than 3:
```
byte strings (b'..') require 3+
```
While this is true in some sense due to [PEP3112](https://www.python.org/dev/peps/pep-3112/) it's also a fact that Python 2.6+ [defines `bytes` as a synonym for `str`](https://docs.python.org/3/whatsnew/2.6.html#pep-3112-byte-literals) and accepts byte literals.

**To Reproduce**
Analyze any Python file that defines a byte literal

**Expected behavior**
Since the syntax for byte literals is allowed from Python 2.6+ I would expect the requirements to be Python 2.6+, not Python 3+

**Environment (please complete the following information):**
 - Vermin version: 0.9.0

**Additional context**
Nothing relevant to report

**Comment by netromdk** [comment]
Thanks for the feedback.

The reasoning for the 3+ requirement is that the abstract syntax tree, parsed by Python itself, interprets `b'..'` directly as a string.

For example, if a file consists of `b'test'` then the AST in Python 2.6+ would be:
```
Module(body=[Expr(value=Str(s='test'))])
```
While in 3+, it would be:
```
Module(body=[Expr(value=Bytes(s=b'test'))])
```

This is why I cannot even detect them in Vermin in 2.6+. But it does make sense since byte strings in 2.6+ are strings and not byte strings, so stating them to be byte strings would be incorrect.

**Comment by alalazo** [comment]
> The reasoning for the 3+ requirement is that the abstract syntax tree, parsed by Python itself, interprets b'..' directly as a string.

Thanks for the explanation, I understand it may be difficult to work around this issue. Based on the insight you gave above on the AST, I just verified that the results of `vermin` are different if the tool is run from a 3+ interpreter  compared to a 2.6+ interpreter. Using this simple module:
```python
s = b'test'
```
this is the result running `vermin` from Python 2.7:
```console
$ python --version
Python 2.7.17

$ vermin -vvvv ~/tmp/vermin/bytelit.py 
Detecting python files..
Analyzing using 4 processes..
~2, ~3       /home/culpo/tmp/vermin/bytelit.py
Minimum required versions: ~2, ~3
```
while this is the result running the same command with a 3.7 interpreter:
```console
$ python --version
Python 3.7.6

$ vermin -vvvv ~/tmp/vermin/bytelit.py 
Detecting python files..
Analyzing using 4 processes..
!2, 3.0      /home/culpo/tmp/vermin/bytelit.py
  L1: byte strings (b'..') require 3+

Minimum required versions: 3.0
Incompatible versions:     2
```

> But it does make sense since byte strings in 2.6+ are strings and not byte strings, so stating them to be byte strings would be incorrect

I don't know if I agree with that. There are plenty of expressions that are valid in Python 2.6+ and 3+ but change semantics. Also, as reported above, `vermin` is currently returning different results based on the interpreter which is used to run the tool which is probably not what is expected. A workaround for my particular case could be to run `vermin` from a Python 2.7 interpreter, but I would still consider this a bug.

**Comment by netromdk** [comment]
While I understand the confusion, it is actually expected (at least on my behalf) that the results differ given the version of Python used. The choice to use Python's own, native parser was done for maintainability and extensibility; all new features are automatically supported. This is also why I recommend using the version of Python matching the minimum version required of a project or higher, of course. This should probably be added to the README.

With that being said, if you chose Python 3.x it would state that byte strings are incompatible with 2.x. But reading [PEP 3112](https://docs.python.org/3/whatsnew/2.6.html#pep-3112-byte-literalsl) again, I might be inclined to change the `b'..'` rule to `((2, 6), (3, 0))` since the syntax is accepted, though rewritten, and works as expected. Just note that Python 2 still sees them as regular strings so Vermin will not impose any restrictions.

I think the following, updated response conveys the meaning?
```
2.6, 3.0     /tmp/bytes.py
  L1: byte strings (b'..') require 3+ (or 2.6+ as `str` synonym)
```

The absence of this rule change is why you use Python 2.7 for https://github.com/spack/spack/pull/14289?

**Comment by alalazo** [comment]
> The absence of this rule change is why you use Python 2.7 for spack/spack#14289?

Yes. Thank you for the response.

**Comment by netromdk** [comment]
I've merged the fix into `master` branch now, and uploaded version 0.9.1 to PyPi if you want to switch to using Python 3.x.

**Comment by alalazo** [comment]
Thanks @netromdk !
