### ISSUE TITLE
Vermin configuration file

### ISSUE THREAD

**Issue by gousaiyang** [netromdk/vermin#56]
Many tools support loading configuration from config files in addition to command line arguments (e.g. [flake8](https://flake8.pycqa.org/en/latest/user/configuration.html), [mypy](https://mypy.readthedocs.io/en/stable/config_file.html), [pytest](https://docs.pytest.org/en/stable/customize.html)). It would be good if `vermin` can also do this. In some sense, declaring project configuration in a config file is more clear and discoverable than saving command line arguments in a script or `Makefile`, and is much better than typing out the command line arguments manually in the long term.

**Proposed config file name and format**

- Many tools have chosen the INI format, and put all configuration items in one specific section. For `vermin` the file name could be `vermin.ini` and the section name could be `vermin`.
- Tools tend to look for multiple files to find configuration (e.g. `toolname.ini`, `setup.cfg`, `tox.ini` and such). This allows a project to put configuration for different tools in different sections in a single file like `setup.cfg`. For `vermin`, it is a good start to only look at `vermin.ini`, and this may be extended in the future.
- Tools may look for a config file in the "containing directory" of processed files and the parent directories. For `vermin`, to simplify, it is a good start to only look at the current working directory (assuming users are running `vermin` in project root), and this may be extended in the future.

Here is a sample `vermin.ini`:

```ini
[vermin]
# declaring minimum compatible version in a config file is good
target = 3.4

# key names in the INI file can be the same as the "long form" argument name in CLI
exclude = foo.bar.baz
backport = argparse,typing

# alternative way to express arrays:
backport =
    argparse
    typing
# this is supported by flake8 and pytest, not sure how INI format handles arrays

feature = fstring-self-doc
```

**Configuration priority**

- When using CLI, manually passed command line arguments override the items in the config file
- When using the Python API, we may have two options:
  - Don't read the config file at all
  - Manually passed config objects override the items in the config file (Does it make sense to look for a config file in the current working directory? We're passing code strings and not dealing with any files.)

Finally, it could be good to print a verbose message like "loading configuration from file ..." when a configuration file is discovered and used. This will let users know that a config file is in effect and help them diagnose configuration problems.

**Comment by netromdk** [comment]
Thanks for the suggestion. I've been thinking about this but didn't know if anybody really wanted it. I guess there are.. :-)

These days I don't use INI format much but it would be very easy to implement using `configparser`. But it could also be done in JSON though that doesn't support standard comments whereas INI supports this. Maybe INI is the more pythonic way.

I agree about showing if it is loading a config file. Wrt. the API, it already takes a `Config` object so I would argue that it shouldn't do anything else than what it does now (since these things are directly like how the internal detector and processor calls things). Therefore, the config detection and use is solely for the CLI of Vermin IMO.

But in any case, I will look into implementing a config.

**Comment by gousaiyang** [comment]
> Wrt. the API, it already takes a `Config` object so I would argue that it shouldn't do anything else than what it does now (since these things are directly like how the internal detector and processor calls things). Therefore, the config detection and use is solely for the CLI of Vermin IMO.

I agree with this.

> But in any case, I will look into implementing a config that would probably be named `vermin.ini`. As for a resolution scheme, I think it should first look in `.`, then check parent folders upward until reaching a "project root" (this is normally if it encounters `.git` and such folders or files), and if that doesn't find anything it should look in `~`.

If we also look at `~`, then it might be good to have a command line argument like `--no-config-file` to suppress loading config files and only use arguments manually provided in CLI.

**Comment by netromdk** [comment]
I like the idea with `--no-config-file`, and maybe even an explicit path to a config when overruling is warranted: `--config-file <path>`.

**Comment by gousaiyang** [comment]
A design question regarding this: should `--exclude-file` and *the files to analyze* (positional arguments `<python source files and folders..>` on CLI) also be specified in the config file? If so, then the file paths specified should probably be relative to the config file location rather than the current working directory. (Generally people should put config files at project root. If a config file is in a subdirectory, usually that means the config only applies to that subdirectory and file outside that subdirectory should not be analyzed).

**Comment by netromdk** [comment]
Funny timing of your message :-)

I was just about to write that I've been working on the functionality for a bit now: https://github.com/netromdk/vermin/compare/dev...config-file

- `--config-file` (`-c`)  will take a config file to load. And it will load it before any other arguments passed, which will change the configuration from the file no matter the ordering of arguments.
- Vermin automatically tries to detect a `vermin.ini` or `vermin.conf`, which it will apply first just like if `--config-file` was passed. Note that if both a `vermin.ini`, for instance, is auto-detected and `--config-file` is specified, then it prefers the `--config-file`.
- `--no-config-file` will disallow `--config-file` and it will not use an auto-detected config file.
- I added a [sample config](https://github.com/netromdk/vermin/blob/config-file/sample.vermin.ini).

Would you mind trying it out? It's still an early version, though.

> A design question regarding this: should --exclude-file and the files to analyze (positional arguments <python source files and folders..> on CLI) also be specified in the config file?

Currently I've implemented it like this:
```ini
### Exclusions ###
# Exclude full names, like 'email.parser.FeedParser', from analysis. Useful to ignore conditional
# logic that can trigger incompatible results. It's more fine grained than lax mode.
#
# Exclude 'foo.bar.baz' module/member: foo.bar.baz
# Exclude 'foo' kwarg:                 somemodule.func(foo)
# Exclude 'bar' codecs error handler:  ceh=bar
# Exclude 'baz' codecs encoding:       ce=baz
#
# Example exclusions:
#exclusions =
#  email.parser.FeedParser
#  argparse.ArgumentParser(allow_abbrev)
```

You cannot give a file with exclusions because I felt like the config file is already a file that you then specify exclusions in. But you can write all the exclusions in `exclusions = ..`.

The file path to `--exclude-file <file>` is loaded as it's provided. The contents of the file is just lines of exclusions, like what can be specified in the config file.

If they put `vermin.ini` in a subfolder then it will currently not be detected since it detects from the folder Vermin is called from and upwards. I thought about whether it should check all folders that specified input files on CLI for `vermin.ini`, too, and similarly proceed upwards like it already does. But that's actually difficult because that means parsing all arguments _first_ in order to know which values of `sys.argv` are arguments and what's left are the file paths to detect minimum rules in. But I'm still a bit undecided about this current behavior and whether it should be changed or not.

**Comment by gousaiyang** [comment]
Oh for the `--exclude-file` parameter, I've misunderstood its meaning. I thought it is excluding certain files from analysis rather than reading `--exclude` args from a file (instead of from CLI). Excluding certain files from analysis could be useful to some extent, if a project has some files with `.py` extension which are test cases (data) for static analysis rather than code to be executed.

As for `vermin.ini` detection in subfolders, I thinks it's fine not to check all subfolders based on file paths specified in `sys.argv`. The user can easily specify the config file in the subfolder via `--config-file`, or simply do a `chdir` before executing `vermin`. And it's fine to only recognize one config file instead of allowing multiple config files (and the one in the subfolder overrides the one in the root folder). Otherwise the design would be complicated.

**Comment by gousaiyang** [comment]
Probably some negative CLI args are needed (such as `--no-quiet`, `--no-lax`, `--no-hidden`) to override (reset) the true values in the config file?

Also the pessimistic mode might be problematic with the current file detection heuristics. Running `vermin` against its own codebase with `--pessimistic` will detect `misc/actions/test.sh` and report it as `~2, !3`. But it is obvious that it's not a Python file because it has a `.sh` extension (and a non-Python shebang `#!/bin/bash`). Maybe the file detection heuristics could be updated to incorporate some of the following ideas:

- If a file has neither a Python extension or a Python shebang, do not analyze it.
- If a file has some known extensions that are not likely to be Python files (e.g. `*.sh`, `*.md`, `*.rst`, `*.txt` or `Makefile`), do not analyze it.

Or maybe allow users to manually exclude certain files for analysis.

**Comment by netromdk** [comment]
Good idea with the `--no-X` arguments. Will implement those.

It actually also happens without pessimistic mode. The thing is that some put their Python code in shell scripts and expect Vermin to work with it.. But it might make sense to check if there is a shebang, and then only parse it if it includes "python". I'm already [excluding certain extensions](https://github.com/netromdk/vermin/blob/master/vermin/detection.py#L10), where `md` and `rst` are part of that list. Maybe `txt` should be added. `Makefile` will already not be checked. Note that all files specified directly as arguments will be checkd, of course.

Yeah, maybe as a later feature it could make sense to add something like `--exclude-ext sh` and `exclude-exts = ..` in the config.

Both of the last two things will be separate to this branch, though.

**Comment by netromdk** [comment]
I've pushed the following arguments that negate:
* `--no-quiet`
* `--no-ignore`
* `--no-lax`
* `--no-hidden`
* `--no-pessimistic`

**Comment by netromdk** [comment]
Do you have other feedback?
Otherwise I'll merge it to `dev` later today.

**Comment by gousaiyang** [comment]
1. There should probably be a `--show-tips` argument to negate `--no-tips`. Maybe also `--no-target` to clear the target set by config file?
2. It would be better to mark which arguments are the default action, like:
```
--hidden ...
--no-hidden (default) ...
--show-tips (default) ...
--no-tips ...
```
3. For array-valued config attributes (`--exclude`, `--backport`, `--feature`), what should be the correct action if the user supplied it both in the config file and in command line arguments? For example:
```
backports =
  typing
  argparse
```
with `--backport dataclasses`.

Should it override or merge the values?
- Override: the final value for `backport` is `['dataclasses']`
- Merge: the final value for `backport` is `['typing', 'argparse', 'dataclasses']`

I'm not sure which one a user could expect. If the user wants to merge but the action is to override, they need to write `--backport typing --backport argparse --backport dataclasses`. If the user wants to override but the action is to merge, they need to write `--no-backport --backport dataclasses` (clear old value before setting new value, which is probably a bit weird).

**Comment by netromdk** [comment]
Thanks. I've pushed:
* Showing `(default)` in help for the default arguments
* `--show-tips`
* `--dump` (only had `-d` before)
* `--no-dump`
* `--no-target`

It's a very good question about whether it should override or merge. Currently it will merge, so it will be `['typing', 'argparse', 'dataclasses']` for your case above. I somehow feel that is most natural. So assuming merge stays, would the user then expect `--no-backports`, `--no-excludes`, and `--no-features` to be able to reset?

**Comment by netromdk** [comment]
Pushed:
* `--no-backport`
* `--no-exclude`
* `--no-feature`

**Comment by netromdk** [comment]
`config-file` has been merged into `dev`.

If you don't have more feedback then I will close this issue, @gousaiyang

**Comment by netromdk** [comment]
Btw I've pushed a fix for the incorrect magic line detection you [mentioned](https://github.com/netromdk/vermin/issues/56#issuecomment-731443914) via https://github.com/netromdk/vermin/commit/6817076704269a96d9c5308d1dba12252bfb7a5b.

**Comment by gousaiyang** [comment]
Looks good

**Comment by netromdk** [comment]
Thanks!
