### ISSUE TITLE
Vermin reports 3.6 instead of 3.8 on files with self-documenting f-strings

### ISSUE THREAD

**Issue by lou1306** [netromdk/vermin#77]
**Describe the bug**
Vermin fails to detect self-documenting f-string syntax, so its result may not accurately report the minimum Python version required to run a script. Specifically, these f-strings are a Python 3.8 feature, but Vermin reports 3.6.

**To Reproduce**
Run Vermin on a file containing a self-documenting f-string. This can be as easy as the following script:

```python3
a = 10
print(f"{a=})"
```

Vermin reports Python 3.6 as the minimum required version, but running such code on Python 3.6 or 3.7 will fail with `SyntaxError: invalid syntax`.

**Expected behavior**
Vermin should report 3.8 as the minimum required version to run the code.

**Environment (please complete the following information):**
 - Vermin version: 1.2.2

**Additional context**
This is likely related to issue #39. From that discussion it seems `ast` is not the best way to detect such idioms, because it is essentially syntactic sugar for `f"a={a}"`.

**Comment by netromdk** [comment]
Thanks for reaching out. If you read the [caveats](https://github.com/netromdk/vermin#caveats) section of the readme, it says:
> Self-documenting fstrings detection has been disabled by default because the built-in AST cannot
distinguish `f'{a=}'` from `f'a={a}'`, for instance, since it optimizes some information away
(#39). And this incorrectly marks some source code as using fstring self-doc when only using general fstring. To enable (unstable) fstring self-doc detection, use `--feature fstring-self-doc`.

The project uses the built-in lexer and parser that Python itself uses such that it is always in line with the features of the language - and how to parse them. Unfortunately, it optimizes away important information in the case of self-documenting fstrings, which is why the feature is marked as unstable because it cannot be precise enough without the information.

It's unfortunate but it does not make sense, for the project, to change lexer and parser. That would also incur additional dependencies to the project that changes the minimum version of Python needed to run it.

If you have the following code (you were missing a closing `)`):
```py
a = 10
print(f"{a=})")
```
And run Vermin with the feature enabled, you'll get:
```sh
% ./vermin.py -vv --feature fstring-self-doc test.py
Detecting python files..
Analyzing using 8 processes..
!2, 3.8      /tmp/test.py
  f-strings requires !2, 3.6
  print(expr) requires 2.0, 3.0
  self-documenting fstrings requires !2, 3.8

Minimum required versions: 3.8
Incompatible versions:     2
```

**Comment by lou1306** [comment]
Sorry, I totally missed the caveats. I will use `--feature fstring-self-doc` in the future. Thanks!

**Comment by netromdk** [comment]
Great. No worries!
